language: objective-c

before_install:
  - brew update
  - brew install xctool
  - cd Project
  - pod install

script: xctool -workspace KISObserver.xcworkspace -scheme KISObserver build test -sdk iphonesimulator