language: objective-c

before_install:
  - gem install cocoapods --no-doc
  - brew update
  - brew uninstall xctool && brew install xctool
  - cd Project && pod install

xcode_workspace: KISObserver.xcworkspace
xcode_scheme:    KISObserver
xcode_sdk:       iphonesimulator